### ISSUE TITLE
Drive.delete returning undefined

### ISSUE THREAD

**Issue by thiagopinheirolima** [adonisjs/adonis-drive#4]
The following code is returning undefined, it **works**, but the **returning is not working**
`const test = await Drive.delete(filepath)`

**Comment by thetutlage** [comment]
Seems to be returning `true` for me. Are you testing the output of `test` variable?

**Comment by thiagopinheirolima** [comment]
I'm using Windows, are you using Linux/Mac?

**Comment by thetutlage** [comment]
Can u share the actual code?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by nwashangai** [comment]
@thetutlage 
mine returns true but doesn't delete the file
`const sure = await Drive.delete(Helpers.tmpPath('uploads/avatar' + fileName))`
please help me if you can
