### ISSUE TITLE
Add New Driver

### ISSUE THREAD

**Issue by borie88** [adonisjs/adonis-drive#5]
Hello, I'm trying to add Aliyun OSS support to Drive, but have no idea how to add a new driver using the extend method. Any chance someone could explain how the file structure should look like, how to register the new driver, etc? Thanks!

**Comment by antwaanvh** [comment]
Hi @borie88,

Adonisjs uses [node-flydrive](https://github.com/Slynova-Org/node-flydrive) under the hood. You might consider adding a pull request there.

**Comment by borie88** [comment]
@antwaanvh Pull request made -- thanks!
