### ISSUE TITLE
Cannot find module 'aws-sdk/clients/s3'

### ISSUE THREAD

**Issue by mtnptrsn** [adonisjs/adonis-drive#7]
I have installed adonis-drive via:
`adonis install @adonisjs/drive`

My env file has these props:
```
S3_KEY="MY_S3_KEY"
S3_SECRET="MY_SECRET_KEY"
S3_BUCKET="MY_BUCKET"
S3_REGION="eu-central-1"
```

The `config/drive.js` file has been created automatically and I have set `default: 's3'` in there.

The problem:
When I run:
`adonis repl`
`const Drive = use('Drive')`
`await Drive.exists('unicorn.jpg')`

I get: `Error: Cannot find module 'aws-sdk/clients/s3'`

What have I done wrong here? Or is this a bug?

Thanks.

**Comment by mtnptrsn** [comment]
Installing `aws-sdk` in my project obivously works, but I guess this should be included by default.

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
